services:
  jaeger:
    image: 'cr.jaegertracing.io/jaegertracing/jaeger:2.14.1'
    ports:
      - '4317'
      - '16686:16686'
  otelc:
    image: 'ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.144.0'
    ports:
      - '4317:4317'
    volumes:
      - './etc/otelc.yml:/etc/otelcol-contrib/config.yaml'
    environment:
      JAEGER_HOST: 'jaeger:4317'
