---
name: CI
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
env:
  AQUA_CONFIG: ${{ github.workspace }}/aqua.yaml
  AQUA_POLICY_CONFIG: ${{ github.workspace }}/aqua-policy.yaml
jobs:
  ok:
    needs:
      - public-test
      - public-lint
      - backend-test
    if: failure()
    permissions: {}
    runs-on: ubuntu-24.04
    steps:
      - run: exit 1
  public-test:
    name: "public: test"
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm -r test
      - uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
        with:
          version: v0.74.1
          config: ${{ github.workspace }}/.github/octocov.public.yml
          work-dir: ${{ github.workspace }}/public
  public-lint:
    name: "public: lint"
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.56.1
      - continue-on-error: true
        run: pnpm -s -r lint > out.txt
      - env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: reviewdog -f eslint -fail-level any -filter-mode nofilter -reporter github-pr-review < out.txt
  backend-test:
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        id: setup-go
        with:
          cache: true
          go-version-file: go.mod
      - run: go mod download
      - name: go test
        run: go test -coverpkg=./... -coverprofile=./coverage.out -timeout=30s ./backend/...
      - uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
        with:
          version: v0.74.1
          config: ${{ github.workspace }}/.github/octocov.backend.yml
